# Generated by Django 2.1.7 on 2020-02-18 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stusapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Strus Post', 'verbose_name_plural': 'Status Posts'},
        ),
    ]
