# Generated by Django 2.1.7 on 2019-05-11 21:27

from django.db import migrations, models
import libraryapps.models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=libraryapps.models.upload_image_path),
        ),
    ]
